services:
  getaround-api:
    container_name: getaround-api
    image: getaround-api
    build: ${PWD}/api
    restart: unless-stopped
    volumes:
      - ${PWD}/api/app.py:/api/app.py
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    networks:
      - getaround

  getaround-dashboard:
    container_name: getaround-dashboard
    image: getaround-dashboard
    build: ${PWD}/dashboard
    restart: unless-stopped
    volumes:
      - ${PWD}/dashboard/app.py:/dashboard/app.py
    environment:
      - PORT=4000
    ports:
      - "4001:4000"
    networks:
      - getaround

  getaround-mlflow:
    container_name: getaround-mlflow
    image: getaround-mlflow
    build: ${PWD}/mlflow
    restart: unless-stopped
    environment:
      - PORT=4000
    ports:
      - "4002:4000"
    networks:
      - getaround

networks:
  getaround:
